export const DISPLAY_ALERT = 'SHOW_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

export const SETUP_USER_BEGIN = 'SETUP_USER_BEGIN';
export const SETUP_USER_SUCCESS = 'SETUP_USER_SUCCESS';
export const SETUP_USER_ERROR = 'SETUP_USER_ERROR';

export const GET_TOURS_BEGIN = 'GET_TOURS_BEGIN';
export const GET_TOURS_SUCCESS = 'GET_TOURS_SUCCESS';
export const GET_TOURS_ERROR = 'GET_TOURS_ERROR';

// export const GET_TOUR_BEGIN = 'GET_TOUR_BEGIN';
// export const GET_TOUR_SUCCESS = 'GET_TOUR_SUCCESS';
// export const GET_TOUR_ERROR = 'GET_TOUR_ERROR';

export const GET_CURRENT_USER_BEGIN = 'GET_CURRENT_USER_BEGIN';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';

export const LOGOUT__USER = 'LOGOUT__USER';
